project:
  type: website

website:
  title: "LA Bachelors Degrees"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - class-june-19.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



